// <auto-generated />
namespace Site22.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Sedasd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sedasd));
        
        string IMigrationMetadata.Id
        {
            get { return "202005111951092_Sedasd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
