// <auto-generated />
namespace Site22.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Fixing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fixing));
        
        string IMigrationMetadata.Id
        {
            get { return "202005232139233_Fixing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
